ignored_providers = ["files", "nirisessions", "runner"]

bookmarks.location = "/home/voznik/Bookmarks/buku/bookmarks.csv"

[[bookmarks.categories]]
name = "work"
prefix = "w:"

[[bookmarks.categories]]
name = "personal"
prefix = "p:"
