GOOSE_MODE: approve
GOOSE_RECIPE_PATH: $HOME/.ai/recipes
GOOSE_PROMPT_PATH: $HOME/.ai/prompts
OLLAMA_HOST: localhost
GOOSE_PROVIDER: gemini-cli
GOOSE_MODEL: gemini-2.5-pro
GEMINI_CLI_COMMAND: gemini
extensions:
  developer:
    enabled: true
    type: builtin
    name: developer
    description: Code editing and shell access
    display_name: Developer Tools
    timeout: 500
    bundled: true
    available_tools: []
  extensionmanager:
    enabled: true
    type: platform
    name: Extension Manager
    description: Enable extension management tools for discovering, enabling, and disabling extensions
    bundled: true
    available_tools: []
  todo:
    enabled: true
    type: platform
    name: todo
    description: Enable a todo list for Goose so it can keep track of what it is doing
    bundled: true
    available_tools: []
  chatrecall:
    enabled: true
    type: platform
    name: chatrecall
    description: Search past conversations and load session summaries for contextual memory
    bundled: true
    available_tools: []
  memory:
    enabled: true
    type: builtin
    name: memory
    description: Tools to save and retrieve durable memories
    display_name: Memory
    timeout: 250
    bundled: true
    available_tools: []
  context7:
    enabled: true
    type: stdio
    name: context7
    description: ''
    cmd: context7-mcp
    args: []
    envs: {}
    env_keys: []
    timeout: 350
    bundled: null
    available_tools: []
  skills:
    enabled: true
    type: platform
    name: skills
    description: Load and use skills from relevant directories
    bundled: true
    available_tools: []
  code_execution:
    enabled: false
    type: platform
    name: code_execution
    description: Execute JavaScript code in a sandboxed environment
    bundled: true
    available_tools: []
  repomix:
    enabled: true
    type: stdio
    name: repomix
    description: Repomix - Pack repositories into AI-friendly formats
    cmd: repomix
    args:
    - --mcp
    envs: {}
    env_keys: []
    timeout: 250
    bundled: null
    available_tools: []
  basic_memory:
    enabled: true
    type: stdio
    name: basic_memory
    description: s
    cmd: basic-memory
    args:
    - mcp
    envs: {}
    env_keys: []
    timeout: 250
    bundled: null
    available_tools: []
  github-mcp-server:
    enabled: true
    type: stdio
    name: github-mcp-server
    description: GitHub MCP Server
    cmd: github-mcp-server
    args:
    - stdio
    - --log-file=/tmp/github-mcp-server.log
    envs: {}
    env_keys: []
    timeout: 250
    bundled: null
    available_tools: []
CLAUDE_CODE_COMMAND: claude
OPENAI_HOST: https://api.mistral.ai
OPENAI_BASE_PATH: v1/chat/completions
GOOSE_TELEMETRY_ENABLED: false
