[env]
_.file = ['.env', '.env.local', '.env.system']
# 
MISE_NODE_GPG_VERIFY = "false"

[alias]
rust = "core:rust"                    # Use core backend

[tools]
# mise registry
ripgrep = "latest"
gum = "latest"
yq = "latest"
atuin = "latest"
duckdb = "latest"
gh = "latest"
glab = "latest" 
glow = "latest"
# npm registry
node = "24"
"npm:@fission-ai/openspec" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "v0.24.0-preview.0"
"npm:@google/jules" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:repomix" = "latest"
"npm:rulesync" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@karakeep/cli" = "latest"
# MCPs
"npm:@upstash/context7-mcp" = "latest"
#
# pip registry
python= "3.14"
uv = "latest"
poetry = "latest"
cookiecutter = "latest"
ruff = "latest"
"pipx:basedpyright" = "latest"
"pipx:buku" = "latest"
"pipx:basic-memory" = { version = "latest", uvx_args = "--python 3.12" } # IMPORTANT:
"pipx:git+https://github.com/github/spec-kit.git" = "latest"
"pipx:git+https://github.com/oraios/serena.git" = { version = "latest", uvx_args = "--python 3.12" }
# git registry
"github:block/goose" = "latest"
"github:anomalyco/opencode" = { version = "latest" }
"github:dhth/bmm" = "0.3.0"
"github:Inlyne-Project/inlyne" = "latest"
# 
rust = "latest"
"github:cargo-bins/cargo-binstall" = "latest"
lua-language-server = "latest"
stylua = "latest"

#
[settings]
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = ['node']
python.uv_venv_auto = true
pipx.uvx = true
