[env]
_.file = ['.env', '.env.local', '.env.system']
_.path = "{{env.HOME}}/.bun/bin"
# 
MISE_NODE_GPG_VERIFY = "false"
# IMPORTANT USER ENV
LUA_PATH = "{{env.XDG_CONFIG_DIR}}/lua/?.lua;;"

[tool_alias]
rust = "core:rust" # Use core backend

[tools.rust]
version = "latest"

[tools]
# mise registry
ripgrep = "latest"
gum = "latest"
yq = "latest"
atuin = "latest"
duckdb = "latest"
gh = "latest"
glab = "latest"
glow = "latest"
navi = "latest"
# npm registry
node = "24"
bun = { version = "latest", postinstall = "bun install -g tokscale" }
"npm:@fission-ai/openspec" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "0.27.3"
"npm:@google/jules" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:repomix" = "latest"
"npm:rulesync" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@karakeep/cli" = "latest"
"npm:markdownlint" = "latest"
"npm:moltbot" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
# MCPs
"npm:@upstash/context7-mcp" = "latest"
"pipx:basic-memory" = { version = "latest", uvx_args = "--python 3.14" }
"pipx:git+https://github.com/github/spec-kit.git" = "latest"
"pipx:git+https://github.com/oraios/serena.git" = { version = "latest", uvx_args = "--python 3.12" }
"github:github/github-mcp-server" = "latest"
#
# pip registry
python = "3.13"
uv = "latest"
poetry = "latest"
cookiecutter = "latest"
ruff = "latest"
"pipx:basedpyright" = "latest"
"pipx:buku" = "latest"
"pipx:claude-monitor" = "latest"
# gh registry
"github:block/goose" = "latest"
"github:anomalyco/opencode" = { version = "latest" }
"github:tstack/lnav" = { version = "0.14.0-beta2" }
"github:dhth/bmm" = "0.3.0"
"github:Inlyne-Project/inlyne" = "latest"
"github:coollabsio/coolify-cli" = "latest"
"github:nicosuave/memex" = "latest"
"pipx:trilium-alchemy" = "latest"

# 
lua-language-server = "latest"
stylua = "latest"
shfmt = "latest"
taplo = "latest"
act = "latest"
"pipx:mcp-proxy" = "latest"
zola = "latest"
"github:trailbaseio/trailbase" = "latest"
# 
# "http:packages.httpie.io/binaries/linux/http-latest" = { version = "latest", bin = "httpie" }
[tools."http:httpie"]
version = "latest"
url = "https://packages.httpie.io/binaries/linux/http-{version}"
bin = "httpie" # Rename from docker-compose-linux-x86_64 to docker-compose

#
[settings]
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = ['node']
python.uv_venv_auto = true
pipx.uvx = true

[task_config]
dir = "{{cwd}}"
includes = [
  "{{ config_root }}/tasks", # Global tasks available everywhere
]
